FROM python:3.10-buster

# Install requirements
COPY requirements.txt /tmp/requirements.txt
RUN pip install --no-cache-dir -r /tmp/requirements.txt

WORKDIR '/code'
COPY ./ ./

CMD ["gunicorn", "--bind", "0.0.0.0:8080", "wsgi:app"]
